[[headers]]
  for = "/rss.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build]
  command = "npm run netlify"
  functions = "public/functions/"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"
